Repository LaGamma/WalrusWars, pull requests merged in 2019-10, with the labels that each got.

#21 Player death & respawn. Fixed return error.
  application/bin/application.cpp
  application/include/GameLogic.h
  application/src/GameLogic.cpp
  application/src/Stage.cpp
Labels: Sprint 1, bug, critical task

#22 Added simple stage progression
  application/include/GameLogic.h
  application/src/CameraView.cpp
  application/src/GameLogic.cpp
Labels: Sprint 1

#52 use absolute sizing for relative position (for some strange reason)
  application/src/CameraView.cpp
Labels: bug
